### PR TITLE
CLUS-3776 allow path in controller url & remove/update controller by xid instead of url

### PR DESCRIPTION
**Pull request by alexgolod**
jira: https://severalnines.atlassian.net/browse/CLUS-3776

Regarding remove/update by xid
This logic was done before xid was introduced, it is better to xid for these operation.
Also this fixed a bug - was impossible to update controller url

### CODE REVIEW

**Review by pablopnn — APPROVED** [review]
👯‍♀️

**Review by bunin — APPROVED** [review]
don't we need backwards-compatibility? Do we know if anyone uses this?
It should be fine, but if, eg. someone is using this API, and it's not our FE app, and they upgrade, they'll have it broken.
But I guess nobody is doing that.

**Comment by pablopnn** [comment]
> don't we need backwards-compatibility? Do we know if anyone uses this? It should be fine, but if, eg. someone is using this API, and it's not our FE app, and they upgrade, they'll have it broken. But I guess nobody is doing that.

You are right, ABSA is using it but with our ui also, so i think we need to update cmon-proxy-fe too. 

I think the way we release this is that: they are notified when a new docker image is built and published to https://hub.docker.com/repository/docker/severalnines/clustercontrol-manager, and this is done manually.

BTW: just bc you are here, @alexgolod maybe you can update docs in README with this url param fix.

**Comment by alexgolod** [comment]
Hi @bunin @pablopnn 
I have updated readme and also fixed remove controller - it was broken

Also created PR for hydra: https://github.com/severalnines/cmon-proxy-fe/pull/21

**Pull request merged**
